### ISSUE TITLE
Question: Is it possible to add styles to InlineCheckout content

### ISSUE THREAD

**Issue by mysil2** [bambora/checkout-sdk-web#2]
I'm looking into how I can style InlineCheckout content, but I haven't found a way to do it yet. Is it possible/implemented in any way?

A few options I've looked at:
1. 'styles' parameter when initializing InlineCheckout class.
2. '<head bec-delta-fox="">' tag of the iFrame has two stylesheet links pointing to my domain (at least Chrome says so, but I suspect this is to the Bambora domain): 
>link href="vendor.7daa6915a7de23d4e42fbfb4e44be03a.css" rel="stylesheet"
>link href="app.0afdd1d9ce089dab3e5831900a9f02bb.css" rel="stylesheet"
3. Apply styles to the DOM after the iFrame has loaded (I'm not sure if it will work reliable).

If it is not any good solutions to this I guess ModalCheckout is the way to go as I've seen some style examples in the documantation.

**Comment by jesperzach** [comment]
Currently, there's no way to style anything within the iframe. The `styles` parameter is currently unsupported, which is also why it's not part of the documentation.
We plan to add support for this (along with a good amount of other customization options) sometime during Q3/Q4 2018, but I can't make any promises at this point regarding the timeline or the exact feature set to be implemented.

**Comment by ruant** [comment]
Is this the same as https://dev.na.bambora.com/docs/guides/custom_checkout/#custom-checkout-vs-checkout ? Does this North America stuff works for the rest of the world too?

**Comment by jesperzach** [comment]
Hi @ruant. The North American product targets the North American market segment and is only available on the US and Canada. We target the European and global market with the Checkout we describe here: https://developer.bambora.com/europe/checkout/getting-started/introduction.

I would encourage you to get in touch with a sales representative of either of those departments for any further questions regarding our product offering.

Europe/global: https://www.bambora.com/en/en/e-commerce/overview-e-commerce/
North America: https://www.bambora.com/en/us/contact/
