### ISSUE TITLE
A lot of vulnerabilities in package.json

### ISSUE THREAD

**Issue by w3bdesign** [bambora/checkout-sdk-web#6]
found 147 vulnerabilities (24 low, 60 moderate, 60 high, 3 critical) in 3967 scanned packages 
run `npm audit fix` to fix 79 of them.
18 vulnerabilities require semver-major dependency updates.
50 vulnerabilities require manual review. See the full report for details.

**Comment by AllanWLie** [comment]
The issues have now been fixed. Only issues remaining is devDependencies 

Thank you.

Best regards
Allan Lie - Bambora Online A/S
